// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNYaFPKv_NzZfjUkJNZJN2hZnHcJ0OdcE',
    appId: '1:614410360657:web:56d856604bef94bca9a570',
    messagingSenderId: '614410360657',
    projectId: 'kinring-30eb7',
    authDomain: 'kinring-30eb7.firebaseapp.com',
    storageBucket: 'kinring-30eb7.firebasestorage.app',
    measurementId: 'G-HBPVJLL1GG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB3PClf9dNxFIgKdCzmJHh5Y5RwYIOm5M',
    appId: '1:614410360657:android:61cfabf53e317288a9a570',
    messagingSenderId: '614410360657',
    projectId: 'kinring-30eb7',
    storageBucket: 'kinring-30eb7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmEzmGaXldjEt9Ds5wj7FMl-YaUYxbAgU',
    appId: '1:614410360657:ios:936daae8c6587b58a9a570',
    messagingSenderId: '614410360657',
    projectId: 'kinring-30eb7',
    storageBucket: 'kinring-30eb7.firebasestorage.app',
    iosBundleId: 'com.example.kinring',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmEzmGaXldjEt9Ds5wj7FMl-YaUYxbAgU',
    appId: '1:614410360657:ios:936daae8c6587b58a9a570',
    messagingSenderId: '614410360657',
    projectId: 'kinring-30eb7',
    storageBucket: 'kinring-30eb7.firebasestorage.app',
    iosBundleId: 'com.example.kinring',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNYaFPKv_NzZfjUkJNZJN2hZnHcJ0OdcE',
    appId: '1:614410360657:web:a20e2dccd686bfe6a9a570',
    messagingSenderId: '614410360657',
    projectId: 'kinring-30eb7',
    authDomain: 'kinring-30eb7.firebaseapp.com',
    storageBucket: 'kinring-30eb7.firebasestorage.app',
    measurementId: 'G-D39LX5P30D',
  );
}
